# Generated by Django 5.1.6 on 2025-03-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la comuna')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'Comuna',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del país')),
                ('codigo_iso', models.CharField(blank=True, max_length=2, null=True, verbose_name='Código ISO')),
                ('prefijo_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo telefónico')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('tipo_vivienda', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('oficina', 'Oficina'), ('otro', 'Otro')], default='casa', max_length=20, verbose_name='Tipo de vivienda')),
                ('bloque', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bloque')),
                ('departamento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento')),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.comuna', verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'Direccion',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la región')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'Region',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.region', verbose_name='Región'),
        ),
    ]
