# Generated by Django 5.1.6 on 2025-03-01 19:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMetadata',
            new_name='UsersMetadata',
        ),
        migrations.AlterModelTable(
            name='usersmetadata',
            table='users_metadata',
        ),
    ]
