# Generated by Django 5.1.6 on 2025-03-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_rename_usermetadata_usersmetadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmetadata',
            options={},
        ),
    ]
