# Generated by Django 5.1.6 on 2025-03-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_usersmetadata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersmetadata',
            options={'verbose_name': 'User metadata', 'verbose_name_plural': 'User metadata'},
        ),
    ]
