# Generated by Django 5.1.6 on 2025-03-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_alter_usersmetadata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRegistroTerapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expiracion', models.DateTimeField()),
            ],
        ),
    ]
