# Generated by Django 5.1.6 on 2025-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='imagenes/')),
                ('tipo', models.CharField(choices=[('logo', 'Logo'), ('perfil', 'Perfil'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
